name: CI-CD Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

      # 1 Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2 Setup Java
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3 Build Project
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4 Deploy to EC2
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd cicd
            git pull origin main
            docker build -t weather-app .
            docker stop weather-container || true
            docker rm weather-container || true
            docker run -d -p 8080:8080 --name weather-container weather-app
