script: |
  docker pull sachin654321/cicd1:latest

  docker network create weather-net || true

  docker rm -f cicd1-container || true
  docker rm -f mysql-db || true

  docker run -d \
    --name mysql-db \
    --network weather-net \
    -e MYSQL_ROOT_PASSWORD=rootpassword \
    -e MYSQL_DATABASE=weatherdb \
    mysql:8

  docker run -d \
    --name cicd1-container \
    --network weather-net \
    -p 80:8080 \
    sachin654321/cicd1:latest
